### ISSUE TITLE
是否能提供dll源码

### ISSUE THREAD

**Issue by cewno** [00ll00/java_launch_wrapper#1]

**Comment by 00ll00** [comment]
动态库的源码是 src/main/zig/wrapper.zig，在项目文件夹顶层使用`zig build --release=fast`进行编译（需要配置[zig](https://ziglang.org/)开发环境，要求zig版本0.12.x~0.13.x）。

注：x86架构的动态库仍使用c++编译的版本，这是由于zig编译的版本测试未能正常运行。x86动态库源码可以在 commit `6d93154c9b667a48331b7d13a537dbdbf1e2ced5` 中[查看](https://github.com/00ll00/java_launch_wrapper/blob/6d93154c9b667a48331b7d13a537dbdbf1e2ced5/src/main/cpp/ArgLoader.cpp)。

**Comment by cewno** [comment]
啊这。我没用过zig，我以为这只是配置文件之类的，抱歉打扰了
